### ISSUE TITLE
Unable to disable blinking cursor when using iTerm2

### ISSUE THREAD

**Issue by mushmelty** [reobin/typewritten#102]
**Describe the bug**
After installation (using method `npm install -g typewritten`), the cursor blinks despite the iTerm2 setting having blinking cursor disabled. Turning on blinking cursor then turning it off immediately again will give the desired outcome, but the cursor will begin blinking again after any commands are entered.

I've noticed that after entering a command, there is a slight pause before the cursor begins blinking again.

**To Reproduce**
1. Install typewritten via `npm install -g typewritten` in iTerm2
2. Check settings to ensure that Profiles > Text > Blinking cursor is disabled
3. See blinking cursor in terminal

**Expected behavior**
The cursor would be static from initialization, or would remain un-blinking after resetting the settings.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - iTerm2 3.4.2

**Additional context**
Apologies if this bug is really an iTerm2 bug; this theme is easily the best one I've ever seen for oh-my-zsh and I'm baffled by this behavior.

**Comment by reobin** [comment]
Hey @mushmelty !

Good catch, thanks for the bug report.

Since typewritten takes over the user's cursor configuration by default, we need to find a way to take into account the setting for blinking too.

For now, you can fix it for your setup by doing the following:

1. Set your iterm2's cursor to `underline` and turn off blinking
2. Add `export TYPEWRITTEN_CURSOR="terminal"` to your `~/.zshrc` to take cursor configuration off typewritten's hands
3. Restart your terminal (just restarting the `zsh` session might not be enough because the cursor config zsh hook might stay stuck)

**Comment by mushmelty** [comment]
Followed your instructions exactly, and now typewritten is working as expected (no blinking cursor and looking amazing).

One thing I noticed in my `.zshrc` file is that the npm install placed typewritten configuration `# Set typewritten ZSH as a prompt` below the line for `source $ZSH/oh-my-zsh.sh`, and I added my `export TYPEWRITTEN_SYMBOL` and `export TYPEWRITTEN_CURSOR` below the typewritten configuration. I moved all of those lines above the `source` command, which is probably relevant to this issue as well.

I'm so happy it's working as I had wanted. It's the best OMZ theme I've seen out of all the official ones and the extended set. Thank you very much 😎
