### ISSUE TITLE
npm install script not working correctly

### ISSUE THREAD

**Issue by juanCortelezzi** [reobin/typewritten#111]
**Describe the bug**
When installing via npm, `typewritten.zsh` and `async.zsh` were not symlinked to `/usr/local/share/zsh/site-functions` the directory did not exist.
It also created a new .zshrc on my `$HOME` directory, instead of my `$ZDOTDIR` directory.

**To Reproduce**
1. `npm install -g typewritten`

**Expected behavior**
The script should symlynk the corresponding files to `$FPATH`, and respect the `$ZDOTDIR` env variable

**Desktop (please complete the following information):**
- manjaro linux gnome editon

**Additional context**
I was able to install it correctly by symlinking the `typewritten.zsh` file to a directory inside `$FPATH`.
I asume the script did not work correctly because in my machine the directory `/usr/local/share/zsh` did not exist.
What I did not do was to symlink the `async.zsh` file, but it seems to work fine for me, please let me know how much this action could affect performance.

**Comment by reobin** [comment]
Hi @juanCortelezzi !

Thank you for detailing this issue. It's indeed an oversight that should be fixed promptly. Respecting the user's preferences is important when running installation scripts like these ones. If you'd like to contribute to modifying the install script, let me know and I'll gladly help out. Otherwise, I'll work on a solution no worries :).

As for the async.zsh file, it's only required to turn on the async mode. If the file is not found, or not symlinked correctly, the prompt will work fine, but synchronously. As you noticed, the async feature is optional, and honestly, only ever useful in huge repositories, because git commands take a while to execute in there.
