### ISSUE TITLE
How May I Remove the iTerm2's Header as README?

### ISSUE THREAD

**Issue by y1rah** [reobin/typewritten#12]
Header is not always pretty, but I got trouble in setting iterm2 with non-bar style?

Is there any way to achieve the doc's presented style?

^_^ Thanks.

![Xnip2020-04-26_01-04-48](https://user-images.githubusercontent.com/30183249/80285808-fcb85780-8759-11ea-9f77-364b6c3febdc.jpg)

**Comment by reobin** [comment]
Hi @y1rah !

After accessing the iTerm2 preference window `cmd + ,`, the "no title bar" is located at `Profiles > Window > Style`

![Screen Shot 2020-04-25 at 17 13 11](https://user-images.githubusercontent.com/5920450/80291040-1cc72700-8718-11ea-9fb7-e0a883f63dc4.png)

**Comment by y1rah** [comment]
![Xnip2020-04-26_09-22-24](https://user-images.githubusercontent.com/30183249/80294837-88a0a280-879f-11ea-8673-7c6d0c816148.jpg)

Seems work but the corner's round sharper than normal 😂。

**Comment by y1rah** [comment]
I got the idea, to reach a seem corner round effect, we need iterm2 on 10.14 and above as illustrated [here](https://iterm2.com/documentation-preferences-appearance.html).

**Comment by reobin** [comment]
I am not sure about squared vs. rounded corners as mine always had them rounded.

Another thing I did to get that look is add a little bit of padding around the terminal pane so that text is not so close to the sides. You can do that in the `Advanced` tab. Type "margin" in the search input and change the shown values.

![Screen Shot 2020-04-26 at 10 16 27](https://user-images.githubusercontent.com/5920450/80310227-95c18f80-87a7-11ea-8540-39a924fdd3fb.png)

**Comment by y1rah** [comment]
![Screen Shot 2020-04-27 at 12 30 06 AM](https://user-images.githubusercontent.com/30183249/80313580-479ba300-881e-11ea-804f-7e0313f421e4.png)

Thx, margin is just great!

By the way I guess the rounded feature is provided in iterm theme `minimal`.

Meanwhile, by utilizing margin, one should consider terminal's background color to fit editor theme otherwise will make a border box.

^_^

**Comment by y1rah** [comment]
Additionally, if one uses `yabai`,

try:

```
yabai -m config window_border               on
yabai -m config window_border_width         2
```

to reach a rounded border effect.
